# Generated by Django 5.0.1 on 2024-02-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_name', models.CharField(max_length=100)),
                ('sign_email', models.EmailField(max_length=100, unique=True)),
                ('sign_password', models.CharField(max_length=100)),
                ('sign_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_data',
            },
        ),
    ]
